from django.urls import path

from . import views

app_name = "biblioteca"

urlpatterns = [
    path(
        "categorias/",
        views.categoria_listar,
        name="categoria_listar",
    ),
    path(
        "categorias/cadastrar/",
        views.categoria_criar,
        name="categoria_criar",
    ),
    path(
        "categorias/<int:id>/",
        views.categoria_detalhar,
        name="categoria_detalhar",
    ),
    path(
        "categorias/<int:id>/editar/",
        views.categoria_editar,
        name="categoria_editar",
    ),
    path(
        "categorias/<int:id>/excluir/",
        views.categoria_excluir,
        name="categoria_excluir",
    ),
    path(
        "autores/",
        views.autor_listar,
        name="autor_listar",
    ),
    path(
        "autores/cadastrar/",
        views.autor_criar,
        name="autor_criar",
    ),
    path(
        "autores/<int:id>/",
        views.autor_detalhar,
        name="autor_detalhar",
    ),
    path(
        "autores/<int:id>/editar/",
        views.autor_editar,
        name="autor_editar",
    ),
    path(
        "autores/<int:id>/excluir/",
        views.autor_excluir,
        name="autor_excluir",
    ),
    path(
        "usuarios-livros/",
        views.usuario_livro_listar,
        name="usuario_livro_listar",
    ),
    path(
        "usuarios-livros/cadastrar/",
        views.usuario_livro_criar,
        name="usuario_livro_criar",
    ),
    path(
        "usuarios-livros/<int:id>/",
        views.usuario_livro_detalhar,
        name="usuario_livro_detalhar",
    ),
    path(
        "usuarios-livros/<int:id>/editar/",
        views.usuario_livro_editar,
        name="usuario_livro_editar",
    ),
    path(
        "usuarios-livros/<int:id>/excluir/",
        views.usuario_livro_excluir,
        name="usuario_livro_excluir",
    ),

    path(
        "entrar/",
        views.entrar,
        name="entrar",
    ),
    path(
        "sair/",
        views.sair,
        name="sair",
    ),
]
